//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.PayooService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UniGWSRequest", Namespace="UniGWS")]
    [System.SerializableAttribute()]
    public partial class UniGWSRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChecksumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignatureField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIdField, value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RequestTime {
            get {
                return this.RequestTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestTimeField, value) != true)) {
                    this.RequestTimeField = value;
                    this.RaisePropertyChanged("RequestTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Checksum {
            get {
                return this.ChecksumField;
            }
            set {
                if ((object.ReferenceEquals(this.ChecksumField, value) != true)) {
                    this.ChecksumField = value;
                    this.RaisePropertyChanged("Checksum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Operation {
            get {
                return this.OperationField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationField, value) != true)) {
                    this.OperationField = value;
                    this.RaisePropertyChanged("Operation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string RequestData {
            get {
                return this.RequestDataField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestDataField, value) != true)) {
                    this.RequestDataField = value;
                    this.RaisePropertyChanged("RequestData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Signature {
            get {
                return this.SignatureField;
            }
            set {
                if ((object.ReferenceEquals(this.SignatureField, value) != true)) {
                    this.SignatureField = value;
                    this.RaisePropertyChanged("Signature");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UniGWSResponse", Namespace="UniGWS")]
    [System.SerializableAttribute()]
    public partial class UniGWSResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignatureField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ResponseData {
            get {
                return this.ResponseDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseDataField, value) != true)) {
                    this.ResponseDataField = value;
                    this.RaisePropertyChanged("ResponseData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Signature {
            get {
                return this.SignatureField;
            }
            set {
                if ((object.ReferenceEquals(this.SignatureField, value) != true)) {
                    this.SignatureField = value;
                    this.RaisePropertyChanged("Signature");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="UniGWS", ConfigurationName="PayooService.UniGWSSoap")]
    public interface UniGWSSoap {
        
        // CODEGEN: Generating message contract since element name request from namespace UniGWS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="UniGWS/Execute", ReplyAction="*")]
        Domain.PayooService.ExecuteResponse Execute(Domain.PayooService.ExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="UniGWS/Execute", ReplyAction="*")]
        System.Threading.Tasks.Task<Domain.PayooService.ExecuteResponse> ExecuteAsync(Domain.PayooService.ExecuteRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace UniGWS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="UniGWS/Execute2", ReplyAction="*")]
        Domain.PayooService.Execute2Response Execute2(Domain.PayooService.Execute2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="UniGWS/Execute2", ReplyAction="*")]
        System.Threading.Tasks.Task<Domain.PayooService.Execute2Response> Execute2Async(Domain.PayooService.Execute2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Execute", Namespace="UniGWS", Order=0)]
        public Domain.PayooService.ExecuteRequestBody Body;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(Domain.PayooService.ExecuteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="UniGWS")]
    public partial class ExecuteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Domain.PayooService.UniGWSRequest request;
        
        public ExecuteRequestBody() {
        }
        
        public ExecuteRequestBody(Domain.PayooService.UniGWSRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExecuteResponse", Namespace="UniGWS", Order=0)]
        public Domain.PayooService.ExecuteResponseBody Body;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(Domain.PayooService.ExecuteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="UniGWS")]
    public partial class ExecuteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Domain.PayooService.UniGWSResponse ExecuteResult;
        
        public ExecuteResponseBody() {
        }
        
        public ExecuteResponseBody(Domain.PayooService.UniGWSResponse ExecuteResult) {
            this.ExecuteResult = ExecuteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Execute2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Execute2", Namespace="UniGWS", Order=0)]
        public Domain.PayooService.Execute2RequestBody Body;
        
        public Execute2Request() {
        }
        
        public Execute2Request(Domain.PayooService.Execute2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="UniGWS")]
    public partial class Execute2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Domain.PayooService.UniGWSRequest request;
        
        public Execute2RequestBody() {
        }
        
        public Execute2RequestBody(Domain.PayooService.UniGWSRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Execute2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Execute2Response", Namespace="UniGWS", Order=0)]
        public Domain.PayooService.Execute2ResponseBody Body;
        
        public Execute2Response() {
        }
        
        public Execute2Response(Domain.PayooService.Execute2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="UniGWS")]
    public partial class Execute2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Domain.PayooService.UniGWSResponse Execute2Result;
        
        public Execute2ResponseBody() {
        }
        
        public Execute2ResponseBody(Domain.PayooService.UniGWSResponse Execute2Result) {
            this.Execute2Result = Execute2Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UniGWSSoapChannel : Domain.PayooService.UniGWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UniGWSSoapClient : System.ServiceModel.ClientBase<Domain.PayooService.UniGWSSoap>, Domain.PayooService.UniGWSSoap {
        
        public UniGWSSoapClient() {
        }
        
        public UniGWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UniGWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UniGWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UniGWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Domain.PayooService.ExecuteResponse Domain.PayooService.UniGWSSoap.Execute(Domain.PayooService.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public Domain.PayooService.UniGWSResponse Execute(Domain.PayooService.UniGWSRequest request) {
            Domain.PayooService.ExecuteRequest inValue = new Domain.PayooService.ExecuteRequest();
            inValue.Body = new Domain.PayooService.ExecuteRequestBody();
            inValue.Body.request = request;
            Domain.PayooService.ExecuteResponse retVal = ((Domain.PayooService.UniGWSSoap)(this)).Execute(inValue);
            return retVal.Body.ExecuteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Domain.PayooService.ExecuteResponse> Domain.PayooService.UniGWSSoap.ExecuteAsync(Domain.PayooService.ExecuteRequest request) {
            return base.Channel.ExecuteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Domain.PayooService.ExecuteResponse> ExecuteAsync(Domain.PayooService.UniGWSRequest request) {
            Domain.PayooService.ExecuteRequest inValue = new Domain.PayooService.ExecuteRequest();
            inValue.Body = new Domain.PayooService.ExecuteRequestBody();
            inValue.Body.request = request;
            return ((Domain.PayooService.UniGWSSoap)(this)).ExecuteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Domain.PayooService.Execute2Response Domain.PayooService.UniGWSSoap.Execute2(Domain.PayooService.Execute2Request request) {
            return base.Channel.Execute2(request);
        }
        
        public Domain.PayooService.UniGWSResponse Execute2(Domain.PayooService.UniGWSRequest request) {
            Domain.PayooService.Execute2Request inValue = new Domain.PayooService.Execute2Request();
            inValue.Body = new Domain.PayooService.Execute2RequestBody();
            inValue.Body.request = request;
            Domain.PayooService.Execute2Response retVal = ((Domain.PayooService.UniGWSSoap)(this)).Execute2(inValue);
            return retVal.Body.Execute2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Domain.PayooService.Execute2Response> Domain.PayooService.UniGWSSoap.Execute2Async(Domain.PayooService.Execute2Request request) {
            return base.Channel.Execute2Async(request);
        }
        
        public System.Threading.Tasks.Task<Domain.PayooService.Execute2Response> Execute2Async(Domain.PayooService.UniGWSRequest request) {
            Domain.PayooService.Execute2Request inValue = new Domain.PayooService.Execute2Request();
            inValue.Body = new Domain.PayooService.Execute2RequestBody();
            inValue.Body.request = request;
            return ((Domain.PayooService.UniGWSSoap)(this)).Execute2Async(inValue);
        }
    }
}
