//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardMobile:BaseEntity
    {
       
        public int CategoryCardMobileId { get; set; }
        public string Name { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal UnitSellingPrice { get; set; }
        public bool Deleted { get; set; }
        public bool Published { get; set; }
        public int PictureId { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual CategoryCardMobile CategoryCardMobile { get; set; }
    }
}
