//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryCardMobile:BaseEntity
    {
        public CategoryCardMobile()
        {
            this.CardMobile = new HashSet<CardMobile>();
        }
    
  
        public string Name { get; set; }
        public bool Published { get; set; }
        public bool Deleted { get; set; }
        public string PictureUrl { get; set; }
        public int DisplayOrder { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool IsSupportPayment { get; set; }
        public bool IsSupportTopup { get; set; }
        public string DauSo { get; set; }

        public bool IsCardGame { get; set; }
        public bool IsCard { get; set; }
    
        public virtual ICollection<CardMobile> CardMobile { get; set; }
    }
}
