//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider:BaseEntity
    {
        public string ProviderCode { get; set; }
        public string ProviderName { get; set; }
        public string ServiceCode { get; set; }
        public int ServiceId { get; set; }
        public bool Published { get; set; }
        public bool IsOnline { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
