//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanX.Core.Domain.ClickBay
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airline:BaseEntity
    {
       
        public string AirlinesName { get; set; }
        private ICollection<AirlinesCondition> _airlinesCondition { get; set; }
        public virtual ICollection<AirlinesCondition> AirlinesConditions
        {
            get { return _airlinesCondition ?? (_airlinesCondition = new List<AirlinesCondition>()); }
            protected set { _airlinesCondition = value; }
        }
        private ICollection<ArilinesBaggageCondition> _airlinesBaggageCondition { get; set; }
        public virtual ICollection<ArilinesBaggageCondition> ArilinesBaggageConditions
        {
            get { return _airlinesBaggageCondition ?? (_airlinesBaggageCondition = new List<ArilinesBaggageCondition>()); }
            protected set { _airlinesBaggageCondition = value; }
        }
    }
}
