//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanX.Core.Domain.ClickBay
{
    using System;
    using System.Collections.Generic;

    public partial class BookingPriceDetail : BaseEntity
    {
       
        public int BookingInfoFlightId { get; set; }
        public short PassengerType { get; set; }
        public short Quantity { get; set; }
        public string TicketType { get; set; }
        public string CodeFee { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public decimal TotalPrice { get; set; }
    
        public virtual BookingInfoFlight BookingInfoFlight { get; set; }
        public PassengerType PassengerTypes
        {
            get { return (PassengerType)(this.PassengerType); }
            set { this.PassengerType = (short)value; }
        }
    }
}
