//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanX.Core.Domain.ClickBay
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking:BaseEntity
    {

        public Booking()
        {
            this.BookTicketNotes = new HashSet<BookTicketNote>();
        }
        public string ContactName { get; set; }
        public string ContactGender { get; set; }
        public string ContactPhone { get; set; }
        public string ContactEmail { get; set; }
        public string ContactAddress { get; set; }
        public int ContactCountryId { get; set; }
        public string ContactCityName { get; set; }
        public Nullable<System.DateTime> ContactBirthDate { get; set; }
        public string ContactRequestMore { get; set; }
        public string VoucherCode { get; set; }
        public bool RoundTrip { get; set; }
        public Nullable<int> BookingInfoFlightToId { get; set; }
        public Nullable<int> BookingInfoFlightReturnId { get; set; }
        public short Adult { get; set; }
        public short Child { get; set; }
        public short Infant { get; set; }
        public string CurrencyType { get; set; }
        public decimal CurrentcyRate { get; set; }
        public string CallBackUrl { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal TotalFeeAmount { get; set; }
        public decimal TotalTaxAmount { get; set; }
        public decimal TotalFeeOtherAmount { get; set; }
        public decimal TotalBaggageFeeAmount { get; set; }
        public decimal TotalDiscountAmount { get; set; }
        public decimal PaymentAmount { get; set; }
        public short BookingStatusId { get; set; }
        public short PaymentStatusId { get; set; }
        public short PaymentMethodId { get; set; }
        public string ReasonCancel { get; set; }
        public short ContactStatusId { get; set; }
        public int CustomerId { get; set; }
        public Nullable<System.DateTime> CustomerReceivedDate { get; set; }
        public string CustomerNote { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public bool Deleted { get; set; }
        public short ContactPassengerType { get; set; }

        public virtual PasserType PasserType {
            get { return (PasserType)ContactPassengerType; }
            set { this.ContactPassengerType = (short)value; }
        }
    
        public virtual BookingInfoFlight BookingInfoFlight { get; set; }
        public virtual BookingInfoFlight BookingInfoFlightReturn { get; set; }
        public virtual ICollection<BookTicketNote> BookTicketNotes { get; set; }
    }
}
