//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanX.Core.Domain.ClickBay
{
    using System;
    using System.Collections.Generic;

    public partial class BookingPriceDetail : BaseEntity
    {
       
        public int BookingInfoFlightId { get; set; }
        public short PassengerType { get; set; }
        public short Quantity { get; set; }
        public string TicketType { get; set; }
        public decimal PriceTicket { get; set; }
        public decimal PriceCostTicket { get; set; }
        public decimal FeeAmount { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal FeeOtherAmount { get; set; }
        public decimal TotalPrice { get; set; }
        public decimal TotalFee { get; set; }
        public decimal TotalTax { get; set; }
        public decimal TotalFeeOther { get; set; }
    
        public virtual BookingInfoFlight BookingInfoFlight { get; set; }
    }
}
