//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanX.Core.Domain.ClickBay
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketConcession:BaseEntity
    {
      
        public string TicketType { get; set; }
        public bool RoundTrip { get; set; }
        public string PassengerName { get; set; }
        public string FromPlace { get; set; }
        public string ToPlace { get; set; }
        public Nullable<System.DateTime> DepartDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public decimal TicketPrice { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<bool> IsHelper { get; set; }
        public string ContactPhone { get; set; }
        public string ContactEmail { get; set; }
        public string ContactName { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool Deleted { get; set; }
    }
}
