//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Domain.Entity;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=ThanhToanDiDongContext")
        {

        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
           
            base.OnModelCreating(modelBuilder);
        }
    
        public DbSet<CardMobile> CardMobile { get; set; }
        public DbSet<CategoryCardMobile> CategoryCardMobile { get; set; }
        public DbSet<Order> Order { get; set; }
        public DbSet<OrderNote> OrderNote { get; set; }
        public DbSet<PromotionEvent> PromotionEvent { get; set; }
        public DbSet<Provider> Provider { get; set; }
        public DbSet<Service> Service { get; set; }
    }
}
